project:
  type: book
  output-dir: docs

book:
  title: "MKTG402(3) Labs"
  author: "Ahmad Daryanto"
  date: 02/13/2024
  date-format: long
  chapters:
    - index.qmd
    - lab1.qmd
    - lab2.qmd
    - lab3.qmd
    - lab4.qmd
    - lab5.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual