project:
  type: website
  output-dir: docs

website:
  title: "MKTG402(3) Labs"
  
  sidebar:
    style: "floating"
    search: true
    contents:
          - index.qmd
          - lab1.qmd
          - lab2.qmd
          - lab3.qmd
          - lab4.qmd
          - lab5.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  pdf:
    toc: true
    number-sections: true
    colorlinks: true


editor: visual

