project:
  type: website
  output-dir: docs

website:
  title: "MKTG402(3)-Workshops on the Introduction to Quantitative Research Methods"
  sidebar:
    style: "floating"
    search: true

  navbar:
    left:
      - href: index.qmd
        text: Home
      - lab1.qmd
      - lab2.qmd
      - lab3.qmd
      - lab4.qmd
      - lab5.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

