project:
  type: book

book:
  title: "MKTG402(3) Labs"
  author: "Ahmad Daryanto"
  date: "January 2024"
  chapters:
    - index.qmd
    - lab1.qmd
    - lab2.qmd
    - lab3.qmd
    - lab4.qmd
    - lab5.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual